### ISSUE TITLE
Install and configure an operating system of the GNU/Linux family

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-ZVitaliy#2]
Overview
========

In order to have a superior development environment, you need to set up and configure appropriate software yourself. You also need to know how to configure things, where they are in your system and how to survive in that scary black thing with white letters in it — The Terminal.

![](https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero.png)

Let's start by setting up an operating system of the [GNU/Linux OS family](https://www.quora.com/Is-Linux-an-operating-system-or-a-kernel/answer/Hary-Irfantri) (that is based on [a kernel called Linux](https://www.quora.com/Is-Linux-an-operating-system-or-a-kernel/answer/Hary-Irfantri)).
Now, you have two options: use [Fedora] **(recommended)** or some flavor of Ubuntu (like XUbuntu, frequently used by beginners).
It's best to install it directly on your hardware (as a dual-boot, if needed) but you can also try it out in a VM (like [VirtualBox]).
You also choose to stay on macOS if absolutely necessary but you'll still have to learn your way around terminal-based approaches.

The objective of this task is to get familiar with command-line tools and learn to set up software without using any of the GUI software.

Fedora
------
* [ ] Install [Fedora](https://getfedora.org/en/workstation/download/)
* [ ] Learn about DNF/YUM/RPM. [Here](https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/package-management/DNF/) and [there](https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/RPM/). Also: https://fedoramagazine.org/rpm-packages-explained/.
* [ ] [optionally] Add RPM Fusion to your system: https://rpmfusion.org/
* [ ] Install [Kitty terminal emulator](https://copr.fedorainfracloud.org/coprs/gagbo/kitty-latest/)
* [ ] [Install Google Chrome](https://www.if-not-true-then-false.com/2010/install-google-chrome-with-yum-on-fedora-red-hat-rhel/). No GUI-based install, please.
* [ ] Install [Git](https://git-scm.com/download/linux)
* [ ] Install VS Code using [this instruction](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions), **but** without downloading `*.rpm` file from browser.

Ubuntu
------
* [ ] Install [XUbuntu](https://xubuntu.org/)
* [ ] Learn about APT. [Here](https://help.ubuntu.com/lts/serverguide/apt.html.en) and [there](https://help.ubuntu.com/community/AptGet/Howto)
* [ ] Install [Kitty terminal emulator](https://sw.kovidgoyal.net/kitty/binary.html)
* [ ] [Install Google Chrome](https://www.linuxbabe.com/ubuntu/install-google-chrome-ubuntu-18-04-lts) but scroll to the section `"Install Google Chrome on Ubuntu 18.04 LTS from the Command Line"` and use it. No GUI-based install, please.
* [ ] Install [Git from PPA](https://git-scm.com/download/linux)
* [ ] Install VS Code using [this instruction](https://code.visualstudio.com/docs/setup/linux#_installation), **but** without downloading `*.deb` file so find the line `"The repository and key can also be installed manually with the following script:"` and go from there

[Fedora]: https://getfedora.org/
[VirtualBox]: https://www.virtualbox.org/

**Comment by ZVitaliy** [comment]
@webknjaz If I have Git already installed on my macOS, can I skip mark these steps as done?

**Comment by webknjaz** [comment]
If you have Git, check its version and upgrade it to the newest one. It's often outdated (5+ years old) on macOS.

Also, try using Kitty instead of iTerm. As for the code editor — VS Code is quite light-weight so you can start with it and switch to something else later if you want. I'll also ask you to install and learn some basics of Vim in the upcoming tasks.

**Comment by ZVitaliy** [comment]
- [x] Kitty terminal
- [x] VS Code
- [x] Vim
Current Git version 2.25.0
