### ISSUE TITLE
Create an SSH key and add it to GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-ZVitaliy#3]
See:
* https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key (you may omit adding a password)
* https://help.github.com/articles/connecting-to-github-with-ssh/

After completing instructions, post the result of the following command in a comment to this issue:
```shell
ssh -T git@github.com
```

**Comment by ZVitaliy** [comment]
`ssh -T git@github.com`
`The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:=======.`
`Are you sure you want to continue connecting (yes/no)?`
`yes`
`Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.`
`git@github.com: Permission denied (publickey).`

**Comment by webknjaz** [comment]
@ZVitaliy you didn't add the key to your profile. This command output should contain your GitHub username once you successfully complete this.

P.S. For code blocks on GitHub, use triple backticks at the beginning and at the end of the block. Also, add `console` next to your starting marker. So that it'd start with <code>```console</code> and

 end with <code>```</code>.

**Comment by ZVitaliy** [comment]
@webknjaz done
```
$ ssh -T git@github.com
Hi ZVitaliy! You've successfully authenticated, but GitHub does not provide shell access.
```
